### ISSUE TITLE
시놀로지 나스에 설치시 오류가 발생합니다.

### ISSUE THREAD

**Issue by unowenenigma** [yellowgg2/youngs-downloader#1]
우선, 훌륭한 다운로더를 만들어주셔서 감사합니다.

도커-컴포즈로 설치중인데, 스텝16에서 RUN addgroup명령이 꼬이는것 같습니다.

간단히 찾아본 결과, 일부 리눅스 환경에서는 addgroup에 버그가 있어서, groupadd -o 를 이용하여 같은 기능을 수행 할 수 있다고 합니다.

이를 통해, Dockerfile일부를 수정한 결과, 잘 설치되었습니다.

이로인해 다른 환경에서 큰 문제가 발생하지 않는다면, 수정사항이 반영이 되었으면 합니다. 감사합니다.

**Comment by yellowgg2** [comment]
오 감사합니다. 버그 반영하도록 하겠습니다.

**Comment by yellowgg2** [comment]
> 우선, 훌륭한 다운로더를 만들어주셔서 감사합니다.
> 
> 도커-컴포즈로 설치중인데, 스텝16에서 RUN addgroup명령이 꼬이는것 같습니다.
> 
> 간단히 찾아본 결과, 일부 리눅스 환경에서는 addgroup에 버그가 있어서, groupadd -o 를 이용하여 같은 기능을 수행 할 수 있다고 합니다.
> 
> 이를 통해, Dockerfile일부를 수정한 결과, 잘 설치되었습니다.
> 
> 이로인해 다른 환경에서 큰 문제가 발생하지 않는다면, 수정사항이 반영이 되었으면 합니다. 감사합니다.

@TleTuNag 님 감사합니다. 덕분에 버그 수정할 수 있었습니다.

테스트 해보니 시놀로지 나스의 경우 이미 group id가 존재할 수 있네요. `-o`가 non-unique group id 옵션이군요.

다시 한번 감사드립니다.
