### ISSUE TITLE
시놀로지 나스에서 실행이 안됩니다.

### ISSUE THREAD

**Issue by unowenenigma** [yellowgg2/youngs-downloader#2]
안녕하세요. 우선 훌륭한 프로그램을 만들어 주셔서 감사합니다.

이전에 나스에서는 PUID와 PGID가 충돌해서 설치가 안된다고 이슈 남겨드렸는데, 이번에 다시 설치해 본 결과, 

우선 시놀로지의 경우 etc/timezone이 없어서 etc/TZ로 .yml파일에서 경로를 바꿔줘야 했습니다. 이 부분은 시놀로지 OS 버전문제인건지 확실하게 모르겠네요.

그리고 설치 중 경고가 뜨는데, 경고는 dist-youngs-downloader에 파이썬 라이브러리를 설치하면서 뜨는 것 같습니다. 정확한 내용은 아래와 같습니다.(가장 아래 4줄이 경고 내용 입니다.)

Step 22/23 : RUN python3 -m pip install --user -r /comics-downloader/requirements.txt
 ---> Running in 1932d7fa7cad
Collecting appdirs==1.4.4
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting beautifulsoup4==4.9.3
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting black==21.7b0
  Downloading black-21.7b0-py3-none-any.whl (141 kB)
Collecting bs4==0.0.1
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Collecting certifi==2021.5.30
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting charset-normalizer==2.0.4
  Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting click==8.0.1
  Downloading click-8.0.1-py3-none-any.whl (97 kB)
Collecting colorama==0.4.4
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting configparser==5.0.2
  Downloading configparser-5.0.2-py3-none-any.whl (19 kB)
Collecting crayons==0.4.0
  Downloading crayons-0.4.0-py2.py3-none-any.whl (4.6 kB)
Collecting idna==3.2
  Downloading idna-3.2-py3-none-any.whl (59 kB)
Collecting mypy-extensions==0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting pathspec==0.9.0
  Downloading pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting regex==2021.8.3
  Downloading regex-2021.8.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
Collecting requests==2.26.0
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting selenium==3.141.0
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting soupsieve==2.2.1
  Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
Collecting tomli==1.2.1
  Downloading tomli-1.2.1-py3-none-any.whl (11 kB)
Collecting urllib3==1.26.6
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting webdriver-manager==3.4.2
  Downloading webdriver_manager-3.4.2-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py): started
  Building wheel for bs4 (setup.py): finished with status 'done'
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1272 sha256=f30f0b369488254581882f1dfac75e61266ed6effe0cb6f16276860e9e972a24
  Stored in directory: /home/comics/.cache/pip/wheels/75/78/21/68b124549c9bdc94f822c02fb9aa3578a669843f9767776bca
Successfully built bs4
Installing collected packages: appdirs, soupsieve, beautifulsoup4, tomli, regex, click, pathspec, mypy-extensions, black, bs4, certifi, charset-normalizer, colorama, configparser, crayons, idna, urllib3, requests, selenium, webdriver-manager
  WARNING: The scripts black, black-primer and blackd are installed in '/home/comics/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer is installed in '/home/comics/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

경고와는 상관없이 위의 타임존 문제를 변경할 경우 우선 설치는 되는데, 설치 이후 dist-youngs-downloader_1컨테이너에서 어떤 오류가 발생하는지 재부팅이 무한 반복되고 있습니다. 이에 관해서는 로그가 없어서 원인을 파악하지 못했네요. 

배움이 모자라 ssh 터미널상, 또는 시놀로지 웹에서 도커 로그를 확인하는 방법을 모르겠네요.

장황한 글 읽어주셔서 감사드리며, 아무쪼록 조치가 취해지길 바라겠습니다.

**Comment by yellowgg2** [comment]
제가 한번 확인해보고 댓글다시 달도록 하겠습니다

**Comment by yellowgg2** [comment]
@TleTuNag 님 해당 문제를 확인해본 결과, 업데이트 때문인지 모르겠지만 시놀로지에 timezone 파일이 사라졌더라구요? 그래서 아예 로컬 파일에 포함시켰습니다.

그리고 main 프로그램이 계속 재시작 되는 문제는 webdav폴더 권한이 문제였습니다.

1. repo에서 최신 파일들을 받으시고, 
2. 그 중에 `passwd` 파일을 열어 `www-data:x:1000:1000` 항목을 찾아 `1000:1000` 부분을 UID:GID 순으로 변경하시고 저장하신 다음에 설치 하시면 동작이 잘될 것 같습니다. (제 시놀로지 `6.2.4-25556` 버전에서는 잘 동작하는 것을 확인했습니다) [사용법에 2번 항목 참고](https://github.com/yellowgg2/youngs-downloader#%EC%82%AC%EC%9A%A9%EB%B2%95)

혹시 해보시고 문제 있으시면 또 알려주세요.

감사합니다!

**Comment by unowenenigma** [comment]
방금 테스트해 봤는데 잘 됩니다. 감사합니다!

제가 dsm 버전을 적지 않았는데, DSM 7.0.1-42218버전을 사용하고 있습니다.

문제는 없는 것 같습니다만, 설치 중 타임 설정이 2개가 된다는 식으로 경고가 날라오긴 했는데, 실행에는 문제가 없습니다.

다시 한 번 감사의 말씀 올립니다.
