### ISSUE TITLE
서브도메인 및 SSL 인증서 사용가능하게 해주실수 있으신가요?

### ISSUE THREAD

**Issue by thestreetdj** [yellowgg2/youngs-downloader#3]
서브 도메인(역방향프록시) 연결 및 SSL 인증서를 사용가능하게 업데이트 가능한가요?

사용환경은 시놀로지 7.0.1-42218 에 Docker 로 구동중입니다.

**Comment by yellowgg2** [comment]
Komga나 webdav는 지금도 역방향 프록시로 설정하실 수 있습니다. 제가 지금 그렇게 사용 중 이거든요. 역방향 프록시 설정하실때 websocket 헤더도 등록해보셨나요?

**Comment by thestreetdj** [comment]
> Komga나 webdav는 지금도 역방향 프록시로 설정하실 수 있습니다. 제가 지금 그렇게 사용 중 이거든요. 역방향 프록시 설정하실때 websocket 헤더도 등록해보셨나요?

현재 ssl 인증 안된상태에서 시놀로지의 역방향으로 komga 에는 접속이 되는 상태입니다.
websocket 은 생각을 안해봤습니다. 오늘 퇴근후 시도를 해보겠습니다.

**Comment by thestreetdj** [comment]
HTTPS 접속에 대하여 셋팅방법 아시면 부탁드려도 될까요..

**Comment by yellowgg2** [comment]
> > Komga나 webdav는 지금도 역방향 프록시로 설정하실 수 있습니다. 제가 지금 그렇게 사용 중 이거든요. 역방향 프록시 설정하실때 websocket 헤더도 등록해보셨나요?
> 
> 
> 
> 현재 ssl 인증 안된상태에서 시놀로지의 역방향으로 komga 에는 접속이 되는 상태입니다.
> 
> websocket 은 생각을 안해봤습니다. 오늘 퇴근후 시도를 해보겠습니다.

아래 블로그에 나온 방법으로 한번 해보시겠어요?

https://blog.yellowbox.dev/post/synology/synology-reverse-proxy/

전 이 방법으로 설정해서 쓰고 있습니다.

**Comment by yellowgg2** [comment]
> HTTPS 접속에 대하여 셋팅방법 아시면 부탁드려도 될까요..

다른 도메인을 역방향을 통해 https로 연결하신게 있나요?

만약 이번이 처음 시도시라면, 시놀로지에 외부 도메인 인증서 설정은 하셨는지 궁금합니다.

기존에 이미 다른 서비스를 https로 하셨었다면 위에 블로그에 있는 방법은 아실것 같아서 다시 답글달아요. 

혹시 첨하시는 분이면 인증서 설정부터 모르시는게 아닐까 해서요

**Comment by thestreetdj** [comment]
> > HTTPS 접속에 대하여 셋팅방법 아시면 부탁드려도 될까요..
> 
> 다른 도메인을 역방향을 통해 https로 연결하신게 있나요?
> 
> 만약 이번이 처음 시도시라면, 시놀로지에 외부 도메인 인증서 설정은 하셨는지 궁금합니다.
> 
> 기존에 이미 다른 서비스를 https로 하셨었다면 위에 블로그에 있는 방법은 아실것 같아서 다시 답글달아요.
> 
> 혹시 첨하시는 분이면 인증서 설정부터 모르시는게 아닐까 해서요

해결 완료하였습니다. 도움주셔서 감사합니다.
